#!/bin/bash

tput bold; echo "This convenience script will help you configure all the parameters before building your containers"; tput sgr0;

echo -e "\n"

echo -e "What are you going to configure?\n"

echo -e "\t1. Environment Variables"
echo -e "\t2. TLS Certificates"
echo -n "> "
read option

if [ "$option" = "1" ]; then
	./gen-env
fi

if [ "$option" = "2" ]; then
	cd proxy
	./gen-certs
fi

echo "Closing..."
exit 0
