FROM alpine

# Installing python
RUN apk add --update --no-cache python3
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools
RUN pip3 install --no-cache --upgrade flask
RUN pip3 install --no-cache --upgrade pygtail

RUN mkdir /app
RUN mkdir /log

WORKDIR /app

COPY ./logger/app /app

RUN export FLASK_APP=app.py
RUN export FLASK_ENV=development

CMD ["flask", "run", "--host=0.0.0.0"]
