FROM alpine

# Installing python
RUN apk add --update --no-cache python3
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools
RUN pip3 install --no-cache --upgrade paho-mqtt
RUN pip3 install --no-cache --upgrade influxdb
RUN pip3 install --no-cache --upgrade requests

# Adding files
# RUN mkdir app
ADD ./mqtt_app/mqttapp.py /
ADD ./mqtt_app/run.sh /
# COPY ./mqtt_app/requirements.txt /
# COPY ./mqtt_app/run.sh /
# RUN pip3 install -r /requirements.txt
# RUN chmod o+x /run.sh
# WORKDIR /app
# RUN mkdir log
# RUN touch log/logfile.log
CMD ["sh", "/run.sh"]
