FROM alpine

# Installing python
RUN apk add --update --no-cache python3
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools
RUN pip3 install --no-cache --upgrade paho-mqtt

# Adding files
RUN mkdir app
# COPY ./mqtt_app/requirements.txt /
# COPY ./mqtt_app/run.sh /
# RUN pip3 install -r /requirements.txt
# RUN chmod o+x /run.sh
WORKDIR /app
CMD ["python3", "./mqttapp.py"]
