#!/bin/bash

MOSQUITTO_USERNAME=mosquitto
MOSQUITTO_PASSWORD=homepass
INFLUXDB_ADMIN_USER=admin 
INFLUXDB_ADMIN_PASSWORD=adminpassword
INFLUXDB_API_USER=api
INFLUXDB_API_PASSWORD=apipass
TELEGRAM_BOT_TOKEN=token 
AUTH_USERNAME=admin
AUTH_USERPASS=admin
JWT_SECRET_KEY=secret
API_SECRET_KEY=secret

wait_user(){
	tput setaf 3; tput bold; echo -n "Press enter to continue"; tput sgr0;
	read
	echo -e "\n"
}

title(){
	tput setaf 2; tput bold; echo -n "$1: "; tput sgr0;
}

tput setaf 2; tput bold; tput setb 6;
echo "+---------------------------------+"
echo "|ENVIRONMENT file creation Utility|"
echo "+---------------------------------+"
echo -e "\n"
tput sgr0;

wait_user

title "Specify your mosquitto username [$MOSQUITTO_USERNAME]"

read answer

if [[ ! -z "$answer" ]]; then
	MOSQUITTO_USERNAME=$answer
fi


title "Specify your mosquitto password [$MOSQUITTO_PASSWORD]"

read answer

if [[ ! -z "$answer" ]]; then
	MOSQUITTO_PASSWORD=$answer
fi

title "Specify your telegram bot token [$TELEGRAM_BOT_TOKEN]"

read answer

if [[ ! -z "$answer" ]]; then
	TELEGRAM_BOT_TOKEN=$answer
fi


title "Specify your influxdb admin user [$INFLUXDB_ADMIN_USER]"

read answer

if [[ ! -z "$answer" ]]; then
	INFLUXDB_ADMIN_USER=$answer
fi


title "Specify your influxdb admin password [$INFLUXDB_ADMIN_PASSWORD]"

read answer

if [[ ! -z "$answer" ]]; then
	INFLUXDB_ADMIN_PASSWORD=$answer
fi


title "Specify your influxdb api user [$INFLUXDB_API_USER]"

read answer

if [[ ! -z "$answer" ]]; then
	INFLUXDB_API_USER=$answer
fi


title "Specify your influxdb api password [$INFLUXDB_API_PASSWORD]"

read answer

if [[ ! -z "$answer" ]]; then
	INFLUXDB_API_PASSWORD=$answer
fi


title "Specify your monitortool admin username [$AUTH_USERNAME]"

read answer

if [[ ! -z "$answer" ]]; then
	AUTH_USERNAME=$answer
fi


title "Specify your monitortool admin password [$AUTH_USERPASS]"

read answer

if [[ ! -z "$answer" ]]; then
	AUTH_USERPASS=$answer
fi


title "Specify your JWT secret key (default is a random hex token)"

read answer

if [[ ! -z "$answer" ]]; then
	JWT_SECRET_KEY=$answer
else
	JWT_SECRET_KEY=`python3 -c 'import secrets; print(secrets.token_hex())'`
fi


title "Specify your API secret key (default is a random hex token)"

read answer

if [[ ! -z "$answer" ]]; then
	API_SECRET_KEY=$answer
else
	API_SECRET_KEY=`python3 -c 'import secrets; print(secrets.token_hex())'`
fi


cat << EOF > .env
MOSQUITTO_USERNAME=$MOSQUITTO_USERNAME
MOSQUITTO_PASSWORD=$MOSQUITTO_PASSWORD
INFLUXDB_ADMIN_USER=$INFLUXDB_ADMIN_USER
INFLUXDB_ADMIN_PASSWORD=$INFLUXDB_ADMIN_PASSWORD
INFLUXDB_API_USER=$INFLUXDB_API_USER
INFLUXDB_API_PASSWORD=$INFLUXDB_API_PASSWORD
TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
AUTH_USERNAME=$AUTH_USERNAME
AUTH_USERPASS=$AUTH_USERPASS
JWT_SECRET_KEY=$JWT_SECRET_KEY
API_SECRET_KEY=$API_SECRET_KEY
EOF

cat << EOF > ./influxdb/createdb.iql
CREATE DATABASE airquality WITH DURATION 7d
CREATE USER $INFLUXDB_API_USER WITH PASSWORD '$INFLUXDB_API_PASSWORD'
CREATE USER reader WITH PASSWORD 'read'
GRANT READ ON airquality to $INFLUXDB_API_USER 
GRANT READ ON airquality to reader 
GRANT WRITE ON airquality to $INFLUXDB_API_USER 
EOF

tput bold; echo "Done."; tput sgr0;

